const API = 'http://localhost:3000/api';
const ativos = [
  {codigo:'PETR4',nome:'Petrobras PN',tipo:'Ação',preco:'38.45',variacao:'+3.36%',valor:'R$ 1.25',up:true,volume:'R$ 2.5B',pl:'7.80',fav:true},
  {codigo:'VALE3',nome:'Vale ON',tipo:'Ação',preco:'65.30',variacao:'-1.28%',valor:'R$ 0.85',up:false,volume:'R$ 1.8B',pl:'5.20',fav:false},
  {codigo:'ITUB4',nome:'Itaú Unibanco PN',tipo:'Ação',preco:'28.90',variacao:'+1.58%',valor:'R$ 0.45',up:true,volume:'R$ 890M',pl:'9.10',fav:true},
  {codigo:'BBDC4',nome:'Bradesco PN',tipo:'Ação',preco:'14.22',variacao:'+0.80%',valor:'R$ 0.11',up:true,volume:'R$ 560M',pl:'8.90',fav:false},
  {codigo:'ABEV3',nome:'Ambev ON',tipo:'Ação',preco:'11.34',variacao:'-0.34%',valor:'R$ 0.04',up:false,volume:'R$ 310M',pl:'12.40',fav:false},
  {codigo:'MGLU3',nome:'Magazine Luiza ON',tipo:'Ação',preco:'2.15',variacao:'+2.10%',valor:'R$ 0.04',up:true,volume:'R$ 220M',pl:'-',fav:false}
];
function cardAtivo(a){return `<article class="asset-card"><span class="star">${a.fav?'★':'☆'}</span><h3>${a.codigo}<span class="tag">${a.tipo}</span></h3><p class="name">${a.nome}</p><div class="spark ${a.up?'':'red'}"></div><div class="price">R$ ${a.preco}</div><span class="${a.up?'up':'down'}">${a.up?'↗':'↘'} ${a.valor} (${a.variacao})</span><hr><div class="asset-details"><p>Volume<strong>${a.volume}</strong></p><p>P/L<strong>${a.pl}</strong></p></div></article>`}
function renderDashboard(){document.getElementById('favoritosHome').innerHTML=ativos.filter(a=>a.fav).map(cardAtivo).join('');document.getElementById('popularesHome').innerHTML=ativos.slice(0,6).map(cardAtivo).join('')}
function renderPesquisar(){const lista=document.getElementById('listaAtivos'), busca=document.getElementById('buscaAtivo'), total=document.getElementById('totalAtivos');function render(){const termo=(busca.value||'').toLowerCase();const filtrados=ativos.filter(a=>a.codigo.toLowerCase().includes(termo)||a.nome.toLowerCase().includes(termo));total.textContent=filtrados.length;lista.innerHTML=filtrados.map(cardAtivo).join('')}busca.addEventListener('input',render);render()}
function renderFavoritos(){document.getElementById('listaFavoritos').innerHTML=ativos.filter(a=>a.fav).map(cardAtivo).join('')}
const formCadastro=document.getElementById('formCadastro');const formLogin=document.getElementById('formLogin');const msg=document.getElementById('mensagem');
if(formCadastro){formCadastro.addEventListener('submit',async e=>{e.preventDefault();const nome=document.getElementById('nome').value,email=document.getElementById('email').value,senha=document.getElementById('senha').value,confirmar=document.getElementById('confirmarSenha').value;if(senha!==confirmar){msg.textContent='As senhas não conferem.';return}try{const r=await fetch(`${API}/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome,email,senha})});const d=await r.json();msg.textContent=d.mensagem||d.erro;if(r.ok)setTimeout(()=>location.href='login.html',900)}catch{msg.textContent='Não foi possível conectar ao servidor.'}})}
if(formLogin){formLogin.addEventListener('submit',async e=>{e.preventDefault();try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('email').value,senha:document.getElementById('senha').value})});const d=await r.json();if(r.ok){localStorage.setItem('token',d.token);localStorage.setItem('nome',d.nome);location.href='dashboard.html'}else msg.textContent=d.erro}catch{msg.textContent='Não foi possível conectar ao servidor.'}})}
async function carregarPerfil(){const token=localStorage.getItem('token');if(!token)return;try{const r=await fetch(`${API}/usuario`,{headers:{Authorization:`Bearer ${token}`}});const u=await r.json();if(r.ok){perfilNome.textContent=u.nome;perfilEmail.textContent=u.email;nomePerfil.value=u.nome;emailPerfil.value=u.email;document.querySelectorAll('.avatar').forEach(a=>a.textContent=u.nome.charAt(0).toUpperCase())}}catch{}}
function deletarConta(){localStorage.clear();location.href='login.html'}
